# Generated by Django 2.2.2 on 2019-06-11 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMovie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rate',
        ),
    ]
