# Generated by Django 2.2.2 on 2019-06-12 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appMovie', '0002_remove_movie_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMovie.Country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMovie.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMovie.Language'),
        ),
        migrations.AlterUniqueTogether(
            name='movierate',
            unique_together={('user', 'movie')},
        ),
    ]
