# Generated by Django 2.2.2 on 2019-06-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMovie', '0003_auto_20190612_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
