# Generated by Django 2.2.2 on 2019-06-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMovie', '0006_auto_20190613_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieactor',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
