# Generated by Django 2.2.2 on 2019-06-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMovie', '0007_auto_20190613_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedirector',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
