# Generated by Django 2.2.2 on 2019-06-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMovie', '0008_auto_20190613_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(default=''),
        ),
    ]
