# Generated by Django 2.2.2 on 2019-06-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMovie', '0009_auto_20190614_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
