# Generated by Django 2.2.2 on 2019-06-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMovie', '0010_auto_20190614_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='detail',
            field=models.TextField(max_length=300),
        ),
    ]
