# Generated by Django 2.2.2 on 2019-06-19 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMovie', '0013_tokenuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierate',
            name='rate',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
