# Generated by Django 2.2.2 on 2019-06-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMovie', '0015_auto_20190619_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierate',
            name='comment',
            field=models.TextField(default='', max_length=300),
        ),
    ]
