# Generated by Django 2.2.2 on 2019-06-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMovie', '0016_movierate_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names_movies', models.CharField(max_length=200)),
            ],
        ),
    ]
